version: '2'

services:
  app:
    build: .
    image: playit-web
    container_name: playit-web
    network_mode: host
    environment:
      WEBUI_PORT: 8008
    volumes:
      - ./config:/config
      - ../app/backend:/var/app/backend
      - ../app/frontend:/var/app/frontend
    tty: true
    stdin_open: true
